name: Bug Report
description: Something isn't working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please attach the unedited `mangatranslator.log` and source image (if applicable).

  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: log_file
    attributes:
      label: Log file (if applicable)
      description: Drag and drop mangatranslator.log (or mangatranslator.prev.log if restarted) from the root directory here.

  - type: textarea
    id: image
    attributes:
      label: Problematic image (if applicable)
      description: Drag and drop the original source image here.
