name: Bug Report
description: Something isn't working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please attach the unedited `mangatranslator.log`, problematic images, and source images (if applicable).

  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: log_file
    attributes:
      label: Log file
      description: Drag and drop mangatranslator.log (or mangatranslator.prev.log if restarted) from the root directory here.

  - type: textarea
    id: image
    attributes:
      label: Problematic and source images
      description: Drag and drop the problematic and original source images here.
