name: General Discussion
description: Questions, help, or general conversation
labels: ["question"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
